language: node_js
node_js:
  - "node"
  - "9"
  - "8"

before_install:
  - npm install -g greenkeeper-lockfile@2

install: npm install

before_script:
  - greenkeeper-lockfile-update
  - greenkeeper-lockfile-upload

script:
  - npm test
